[package]
name = "fletch-javac65"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "javac65"
path = "src/main.rs"

[dependencies]
fletch-parser = { path = "../parser" }
getopts = "0.2"
lrpar = "0.13"
