[package]
name = "fletch-parser"
version = "0.1.0"
edition = "2021"

[dependencies]
cfgrammar = "0.13"
lrlex = "0.13"
lrpar = "0.13"
fletch-ast = { path = "../ast" }

[build-dependencies]
cfgrammar = "0.13"
lrlex = "0.13"
lrpar = "0.13"
