[package]
name = "fletch-compiler"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "6502-eater-none-javac"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
